### ISSUE TITLE
which sdk needed ?NETSDK1045

### ISSUE THREAD

**Issue by PrestigeDevop** [Eilon/MauiHybridWebView#22]
Hello , vs playing weird , it doesn't use the latest sdk , 

this error showing in my error list;

```NETSDK1045```
```Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0.	HybridWebView	C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	144	
```

here's my info of  ```dotnet --list-sdks```

```
6.0.400 [C:\Program Files\dotnet\sdk]
7.0.302 [C:\Program Files\dotnet\sdk]
8.0.100-preview.4.23260.5 [C:\Program Files\dotnet\sdk]
```
VS doesn't show (install missing sdk -workloads message )

![image](https://github.com/Eilon/HybridWebView/assets/85388342/6da42c52-ef94-4f18-b5fd-f1b9a772048e)

and here's the ```dotnet list package```
output : 
```
Project 'MauiCSharpInteropWebView' has the following package references
   [net7.0-android31.0]: No packages were found for this framework.
   [net7.0-ios15.4]: No packages were found for this framework.
   [net7.0-maccatalyst15.4]: No packages were found for this framework.
   [net7.0-windows10.0.19041]: No packages were found for this framework.
Project 'HybridWebView' has the following package references
   [net7.0]: No packages were found for this framework.
   [net7.0-android31.0]: No packages were found for this framework.
   [net7.0-ios15.4]: No packages were found for this framework.
   [net7.0-maccatalyst15.4]: No packages were found for this framework.
   [net7.0-windows10.0.19041]: No packages were found for this framework.
Project 'MauiReactJSHybridApp' has the following package references
   [net7.0-android31.0]: No packages were found for this framework.
   [net7.0-ios15.4]: No packages were found for this framework.
   [net7.0-maccatalyst15.4]: No packages were found for this framework.
   [net7.0-windows10.0.19041]: No packages were found for this framework.
```
BTW I enabled preview sdks in vs settings : 
 
![image](https://github.com/Eilon/HybridWebView/assets/85388342/e4ad792e-0329-4cb3-922e-9cca8fc9456e)

solutions I tried ;

`dotnet workload update maui`
updated .
tried to remove sdk& runtimes and reinstall them 
-I tried fixing vs with vs tools (`repair`) 
removing `golbal.json `file 

I'm not comfortable with  the `<TargetFrameworks Condition>` in the solution. 

I did : 
`dotnet restore `and 
`dotnet workload restore `  too no luck

**Comment by PrestigeDevop** [comment]
ugh , I went with the trouble of removing the entire vs then reinstalling it , I'm intermediate level but vs sometimes playing weird for me , wish we had dev home before and a button on github project that take configuration easily, step by step interactive tutorials easily  , lol

**Comment by Eilon** [comment]
Hmm, good question. I've been using a 7.0.x SDK on my machine (7.0.300-preview.23179.2 to be precise).

I'm seeing if adding a `global.json` file will help with this: https://github.com/Eilon/HybridWebView/pull/23/files

You could try adding the file locally to the root of the repo and see if that helps.

**Comment by Eilon** [comment]
Hi, this is a bit out of date by now, but the repo has been updated to .NET 8.0 and I added a global.json to set the .NET SDK version as well. Hopefully that resolves any issues.
