### ISSUE TITLE
How to load a network address

### ISSUE THREAD

**Issue by lkd3063601** [Eilon/MauiHybridWebView#25]
This js call the .NET method is  great，but how to load a network address，in an example like the following, the call went wrong

```xaml
 <hwv:HybridWebView  x:Name="myHybridWebView"   Source="http://192.168.1.6:5500/test1.html" />
```

**Comment by Eilon** [comment]
@lkd3063601 can you [enable the browser dev tools](https://github.com/Eilon/MauiHybridWebView/issues/20) and see what the error is, if any? (After enabling the tools, follow the rest of [this guide](https://learn.microsoft.com/aspnet/core/blazor/hybrid/developer-tools?view=aspnetcore-7.0&pivots=android) to launch the tools.)

**Comment by lkd3063601** [comment]
I solved it by modifying your source code, thank you

**Comment by Eilon** [comment]
@lkd3063601 I'm glad you got it fixed! Can you provide info on what you changed to make it work? Is it a bug in HybridWebView?

**Comment by lkd3063601** [comment]
it is not a bug,   HybridWebView nonsupport network address，I changed the code under each platform，and then use it like this:  
 <hwv:HybridWebView x:Name="myHybridWebView"  StartPath="https://www.microsoft.com" HybridAssetRoot=""  />
use replace with “StartPath”  ，can  support network address and  local html
![image](https://github.com/Eilon/MauiHybridWebView/assets/15059204/4dd495f6-b06d-41b7-b345-375a48b14e4a)

**Comment by lkd3063601** [comment]
js call the .NET method  not work on a regular WebView ,so i use your  HybridWebView  ,I found  HybridWebView  nonsupport 
 network address，when i use
` <hwv:HybridWebView  x:Name="myHybridWebView"  Source="https://www.microsoft.com/" />`
an error occurred,therefore, I can only modify your source code to meet my functionality
![image](https://github.com/Eilon/MauiHybridWebView/assets/15059204/8769822c-413a-4b6d-8308-c4e680b2491b)

**Comment by Eilon** [comment]
Interesting. It can be risky to load external content into the HybridWebView because it can potentially give a web site access to invoke C# code in your app. You have to make sure you 100% trust the web site being loaded and/or ensure that there are no dangerous operations that the web site could invoke in your app.
