### ISSUE TITLE
Blazor Integration

### ISSUE THREAD

**Issue by mahmudmihon** [Eilon/MauiHybridWebView#32]
Can I incorporate react app inside Blazor page

**Comment by Eilon** [comment]
Hi @mahmudmihon , I believe it's possible based on an answer I saw here: https://stackoverflow.com/questions/61487266/render-react-component-inside-blazor-page

This repo is for hosting JS-based apps in .NET MAUI. For example, hosting a React or Angular component. This repo doesn't have anything specific for hosting Blazor. For hosting Blazor in a .NET MAUI app you can use the [BlazorWebView](https://learn.microsoft.com/dotnet/maui/user-interface/controls/blazorwebview?view=net-maui-8.0) control that is part of .NET MAUI, and then you could try to add React components to _that_ based on the StackOverflow post I linked above.

For any other issues about how to integrate with Blazor itself, I recommend either asking on StackOverflow for general questions, or if you think you've encountered a bug or have a feature request, you can post it at https://github.com/dotnet/aspnetcore
