### ISSUE TITLE
Question: Is this going to be fully released / merged into MAUI at some point in the future?

### ISSUE THREAD

**Issue by d-philipson** [Eilon/MauiHybridWebView#38]
Kudos on a great component! Just wondering if it's close to being fully released, as I know it's still technically in preview at the minute? Also, is the plan for this to get merged into MAUI or stay as a seperate component? Thanks

**Comment by Eilon** [comment]
Thanks! We do intend for this to be a proper feature in .NET MAUI. So, while for now it's an experiment, we're seeking feedback on whether it's generally useful, and what features it would need for people to consider using it in their apps.
