### ISSUE TITLE
Feature requests: Proxy requests

### ISSUE THREAD

**Issue by rbrundritt** [Eilon/MauiHybridWebView#42]
**Update:**

After some testing I found a solution that appears to address all the features I was originally looking for. Basically, if we have a way to proxy HTTP requests made by the browser to a native method/function in C# and allow setting the response stream/content type, a whole bunch of scenarios open up. Each browser has something similar already which this libraries leverages for the JavaScript communication, but in doing so, we lose this capability. Also this capability is buried at the platform level, so ideally this hybrid web view will allow for a single point of entry for this feature. Here are some example scenarios where this would be useful:

- Create content in native code on the fly, like images, and pass it back to the browser, kind of like a local service.
- Support the reverse of `InvokeJsMethodAsync` and be able to invoke C# code, receive a message and respond back to it. 
- Some mobile apps let the user download content for offline use. This is often stored as a compressed file, like a zip file. Using this feature, you can easily add code to access the zip file, check if a file is inside it, and if it is, pass it back to the browser.
- When using web libraries that request files and we only have the ability to set the URL string. Most web map controls allow you to pass in a string URL with placeholders for custom map tile services, so without this proxy we would have to host the files as flat files in the app as assets or on a server. However, tile sets tend to consist of tens of thousands or more images and a common method to store them is within a sqlite database so that you only have to move around a single file. With this feature we could easily access a sqlite db, query it, and respond accordingly to the web request.
- Currently this library is passing JSON strings around which may not be the most efficient data format in some scenarios. If I had a large array of numbers, passing that back as a binary stream would likely be faster. 

**Original post:**

First off, really liking this library. I looked at a lot of others, but this looks to be the most complete. I've built some pretty advance apps with web browser/view interop in the past and tried out all the features in this library. Here are a couple of feature requests that I think would really help close the gap on a few scenarios:

- Add support for custom extensions. Currently only `.htm`, `.html`, `.js`, `.css` appear to be supported. All other requests are set to text/plain. In my case I want to be able to load in binary files like `.mp3` or `.gltf`, `.glb`
- Add support for asynchronous responses on .NET methods invoked from JS. For clarity, I want to be able to call a .NET method from JS, and have the .NET code set a response that can be received on the JS side (round trip). Basically, the reverse of `InvokeJsMethodAsync`.
- A similar scenario to the above I'd like to support that I think might just work if the above two items are added, is the ability to use this as a local REST service. In my case I'm using a web map control with a local tile imagery. I have thousands of map tiles, and store them in an SqlLite db to make it easier to manage and move around. I want to be able to create a proxy like method where I can run some custom code to generate my response, in this case check to see if the file exists and load it. A similar scenario might be involve wanting to dynamically create an image in native code in response to a request. In this case, the web map control only takes in string URL's, so I can't leverage the JS invoke methods. I was thinking looking for URL's like `https://0.0.0.0/REST/` and having those trigger a suitable handler/callback might make sense.

I contemplated trying to add these things myself, but figured it would be better to start a discussion first, see if this is something you would want included, and what feedback others might have on the implementation. I'm fairly new to Maui development but have done a lot of Windows and Android development, so I should be able to at least figure out those two platforms. 

Thanks!

**Comment by rbrundritt** [comment]
I made a fork of this project and managed to get a solution working in Windows and Android. You can find the fork here: https://github.com/rbrundritt/MauiHybridWebView

In your web app you can create URLs like this: `https://0.0.0.0/proxy?` and then add any query string parameters you want. Those parameters get passed into an C# function as a `Dictionary<string, string>`. If you set the `ResponseStream` and `ContentType` properties of the event args, those will be passed back to the web app.

**Comment by rbrundritt** [comment]
I just pushed an update to the fork and added support for iOS and Mac, but haven't tested them since I don't have a dev machine for Mac. That said, it looked pretty straight forward and similar to the Android implementation. 

I had a thought that might be something to consider for the overall project, and that is to also support POST requested. This would allow for large amounts of data and likely provide more cross platform consistency for data (URL limitations may currently mean one platform allows less data to be transferred in a URL than another). For the movement of JSON, we could switch between GET and POST behind the scenes based on the size of the JSON object to keep things simple for the end user.

**Comment by rbrundritt** [comment]
I made a lot of progress on my fork today. Here is the current status:

**Feature status:**

- Framework for intercepting web requests from WebView in a .NET method and allow the user to send a response stream back. 
- Round trip .NET method invoke capability (reverse of `InvokeJsMethodAsync`). You can now call a .NET method from JavaScript (with or without parameters), and get a response back from .NET to the calling JavaScript function. This is an async feature since you have to wait for the response. Due to WebView limitations of some platforms, I couldn't get the body of POST requests, and had to instead pass input data as an encoded query string parameter. This will likely mean there is a size limit on input data from the JavaScript side. The result is passed as a JSON stream in the response body, so that should allow massive amounts of data to be sent from .NET to JavaScript if needed.
- Added a bunch of samples in the app that leverages these features. Including an interactive map that loads map tiles from an offline Sqlite DB.
- Working and tested in Windows and Android. All features working well, with great performance.
- Code added for iOS and Mac, but untested due to lack of dev environment. It looks like the code is similar to the Android implementation, so I'm fairly confident it works.

**Work left to do:**

- A bit of code clean up.
- Possibly move the new invoke method samples that leverage the proxy to the invoke sample page rather than having them on the proxy sample page.
- Add documentation to code and Readme.

**Comment by HelloooJoe** [comment]
@rbrundritt I love what you've done!

HybridWebView.SendInvokeMessageToDotNetAsync("CallMeFromScriptAsync", ["msg from js", 987])
	.then(result => console.log("Got result from .NET: " + result));

**Comment by rbrundritt** [comment]
@HelloooJoe thanks. I tried to make it in line with the existing api and make it feel like a natural extension.

**Comment by Eilon** [comment]
@rbrundritt this is now merged! Thank you so much for this huge contribution! There are still the follow-up items I mentioned but as of right now everything works on all supported platforms!

🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳

**Comment by rbrundritt** [comment]
Awesome! Thanks for the improvements. I'll delete my fork now so others don't accidently use that.
