### ISSUE TITLE
Release latest version to nuget

### ISSUE THREAD

**Issue by desjoerd** [Eilon/MauiHybridWebView#47]
I see the latest version is published 5 months ago (targeting net7). I see you've made some improvements/commits. Would it be possible to release the latest as preview to nuget?

Saves us copying code :).

**Comment by hansmbakker** [comment]
I see there is a [build pipeline to publish to nuget](https://github.com/Eilon/MauiHybridWebView/actions/workflows/nuget-publish.yml) 👍🏻 
It would help us a lot if we could consume the .NET version via NuGet!

**Comment by Eilon** [comment]
Working on it!

**Comment by Eilon** [comment]
Alright, party time: https://www.nuget.org/packages/EJL.MauiHybridWebView/1.0.0-preview5
