### ISSUE TITLE
allow passing of object and null from HybridWebView.SendInvokeMessageToDotNet("CallMeFromScript", ["msg from js", 987]);

### ISSUE THREAD

**Issue by HobDev** [Eilon/MauiHybridWebView#48]
I am getting a response from payment gateway which I want to send to the C# for further processing like 

```
 var respData = eval("(" + e.data + ")");
document.getElementById("monerisResponse").innerHTML = " Response Code: " +
    respData.responseCode + " Token: " + respData.dataKey + " Bind: " + respData.bin + " Error Message: " + respData.errorMessage;  
 document.getElementById("monerisFrame").style.display = 'none';

HybridWebView.SendInvokeMessageToDotNet("CallMeFromScript", [respData.dataKey, respData.bin]);`
```
But the exception is thrown when any parameter is empty. For example if respData.dataKey have value than respData.errorMessage is empty. But I want to send all the values and check which values are null in the C# code. Also respData.responseCode is throwing exception which I guess is because it is an int.

**Comment by HelloooJoe** [comment]
Check out what https://github.com/rbrundritt/MauiHybridWebView did. You can now make HTTP style requests to .NET MAUI because he created a web proxy.

**Comment by Eilon** [comment]
Indeed there do seem to be some bugs with null/undefined values. Fix coming soon.
