### ISSUE TITLE
Everyone switch to rbrundritt's repo

### ISSUE THREAD

**Issue by HelloooJoe** [Eilon/MauiHybridWebView#50]
What @rbrundritt created is a freaking game changer. I'm an expert in Angular. What he did was make every Angular app I'll ever create Cross-platform because of that new proxy thing new created. Go check it out! 

https://github.com/rbrundritt/MauiHybridWebView

**Comment by hansmbakker** [comment]
I find opening an issue on @Eilon's repo with the title `Everyone switch to rbrundritt's repo` a bit rude. @Eilon put a lot of work in this, which @rbrundritt might have built an improvement upon.

Wouldn't it be a better idea if @rbrundritt's improvements were contributed back to @Eilon's repo if they are an improvement for everyone as you are saying?

**Comment by HelloooJoe** [comment]
@hansmbakker That was very much my intention.

**Comment by rbrundritt** [comment]
I made a pull request with these changes a few weeks ago here https://github.com/Eilon/MauiHybridWebView/pull/43

So my intention very much was to get this feature into Eilon's branch and then delete mine.

**Comment by Eilon** [comment]
FYI to everyone: I'm looking at @rbrundritt 's PR right now and hope to get it merged in soon. I appreciate everyone's enthusiasm and work to help make HybridWebView even better!

For now I'm closing this issue because I plan to merge #43 once I'm done reviewing it.

**Comment by HelloooJoe** [comment]
About time... #stillgrateful

**Comment by Eilon** [comment]
BTW everything is merged in and is available on NuGet: https://www.nuget.org/packages/EJL.MauiHybridWebView/1.0.0-preview6
