### ISSUE TITLE
keyboard does not shown on textboxes

### ISSUE THREAD

**Issue by Efthymios** [Eilon/MauiHybridWebView#59]
Hi Eilon,

First of all i want to thank you for the
control you have created.
I am encountering an issue with the keyboard not appearing when interacting with text boxes using MauiHybridWebView. 
I am using an external url not a static web page inside the project.

Please advice.

Thank you in advance.
Efthymios

**Comment by Efthymios** [comment]
i found the issue and now it works.

**Comment by peterblazejewicz** [comment]
Please close the issue, thx!

**Comment by HelloooJoe** [comment]
@Efthymios what did you do to resolve the issue? I experience the same thing when text boxes are close to the bottom of the screen. I was expecting the native keyboard to act like the new bottom of the screen and push up the DOM but it just hides it. 

![image](https://github.com/Eilon/MauiHybridWebView/assets/20806837/b0555ea7-644b-4eb1-955a-3be6474f300d)

and then when you activate the keyboard it doesn't push up the input field
![image](https://github.com/Eilon/MauiHybridWebView/assets/20806837/e87453ff-94ff-4082-a0d6-b410b18d8294)

However, when you access the app through Chrome (or whatever) it behaves as expected which moves up the input field

**Comment by Efthymios** [comment]
Hi Eilon,

 

Thanks a lot  for your response.

 

The issue was on my code. I put the control in a refreshview and if the IsEnabled is set to false

The keyboard is not shown.

 

  <RefreshView

      x:Name="refreshViewID"

      Refreshing = "OnRefreshViewRefreshing">

      <hwv:HybridWebView

          x:Name="myHybridWebView"

          BackgroundColor="{StaticResource BgColorWebview}"

          HorizontalOptions="FillAndExpand"

          Navigated="myHybridWebView_Navigated"

          VerticalOptions="FillAndExpand" />

  </RefreshView>

 

Best Regards,

 

Efthymios Argyrou

I.T. Manager

Alt-àVie Ltd

Mob: +357 99694191

www.altavie.com.cy

altavie-logo

**Comment by Efthymios** [comment]
Hi,

 

I had put the hybridwebview inside a refreshview.

And if the isenabled property is set to false the keyboard is not shown on textboxes.

 

Best Regards,

Efthymios Argyrou

 

I.T. Manager

Alt-à-Vie Ltd

Mob: +357 99694191

www.altavie.com.cy

logoAltAVie
