### ISSUE TITLE
iOS 18 Page not loading and it shows 'about:blank'

### ISSUE THREAD

**Issue by cmydur** [Eilon/MauiHybridWebView#78]
I have an app that loads a page and is working fine in iOS17.5 and I'm on iOS18 Beta Developer release it stops working. The safari debugger just shows 'about:blank' and where as iOS17.5 shows '0.0.0.0' 

None of the files load in iOS 18, as it can be seen from the WebInspector of Safari 

![Frame 1](https://github.com/user-attachments/assets/e8cdc2bb-35da-48f6-a18d-a9a1ab268519)

**Comment by longnguyenit94** [comment]
![image](https://github.com/user-attachments/assets/2e4c3688-1df4-4367-ab19-c557fe32c704)

hi
Temporarily change it to localhost

**Comment by cmydur** [comment]
Thank you @longnguyenit94 where do I change it ?

**Comment by mtanml** [comment]
@Eilon can you please publish your change to nuget?   Thanks!

**Comment by Eilon** [comment]
> @Eilon can you please publish your change to nuget? Thanks!

The fix should now be available in the latest package: https://www.nuget.org/packages/EJL.MauiHybridWebView/1.0.0-preview7
